language: go
go: "1.11.x"
services:
  - docker
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install: true # don't `go get` a bunch of junk, we'll get it with dep
script:
  - dep ensure -vendor-only
  - bin/docker-build
deploy:
  provider: script
  script: bin/docker-push
  on:
    repo: travis-ci/trvs-operator
    all_branches: true
notifications:
  email: false
