apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: secrets.travis-ci.com
spec:
  group: travis-ci.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: secrets
    singular: secret
    kind: TrvsSecret
    shortNames:
    - tsec
    - ts
