apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: trvssecrets.travisci.com
spec:
  group: travisci.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: trvssecrets
    singular: trvssecret
    kind: TrvsSecret
    shortNames:
    - tsec
    - ts
